### ISSUE TITLE
Blender 2.8

### ISSUE THREAD

**Issue by thehoopercompany** [scaredyfish/blender-rhubarb-lipsync#17]
Hey guys. Can we get a fix for Blender 2.8. This is a really great tool but I cannot for the life of me get it working I just burnt a whole day trying everything I could think of but nothing has worked.

Basically all it does is just stay greyed out and I cannot click the 'run rhubarb' button after creating my pose library..

Thank you for any advise or time.

**Comment by scaredyfish** [comment]
Hi, I'm not sure what your problem is with the information you've provided. The button would be grayed out if you haven't set the Rhubarb Lip Sync executable in the addon preferences.

Make sure you have downloaded Rhubarb Lip Sync - which is a separate download from this addon (https://github.com/DanielSWolf/rhubarb-lip-sync) - and in Preferences -> Add-ons->Rhubarb Lipsync->Rhubarb Lipsync Executable, browse to where you have unzipped Rhubarb Lip Sync, and choose rhubarb.exe on windows, or rhubarb on linux

**Comment by thehoopercompany** [comment]
Thank you for replying. Yes I have done those steps already but it will not
play. I've tried mov8ng it in and out of the add-ons folder and tuning as
administrator to avoid access issues but I get nothing..

**Comment by scaredyfish** [comment]
Another thought about what may be wrong, are you in pose mode?

**Comment by thehoopercompany** [comment]
Ah, i think you were right btw!
